[package]
name = "psymagen"
version = "0.1.0"
authors = ["Lukas Kalbertodt <lukas.kalbertodt@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
bit-set = "0.5"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'ImageData',
  'console',
]
